[general]
copy-command = "wl-copy"
output-filename = "~/Pictures/Screenshots/screenshot-%Y-%m-%d_%H-%M-%S.png"
disable-notifications = false

floating-hack = true
resize = { mode = "size", width = 1200, height = 800 }
