[main]
font=Hack Nerd Font:size=13
initial-color-theme=light

[colors-light]
foreground=383a42
background=fafafa

cursor=fafafa 383a42
selection-foreground=383a42
selection-background=bfceff

# black
regular0=383a42

# red
regular1=e45649

# green
regular2=50a14f

# yellow
regular3=c18401

# blue
regular4=4078f2

# magenta
regular5=a626a4

# cyan
regular6=0184bc

# white / gray
regular7=a0a1a7

# bright black / gray
bright0=696c77

# bright red
bright1=ca1243

# bright green
bright2=50a14f

# bright yellow
bright3=986801

# bright blue
bright4=4078f2

# bright magenta
bright5=a626a4

# bright cyan
bright6=0184bc

# bright white / darkest text
bright7=090a0b
