[main]
font=Hack Nerd Font:size=12
initial-color-theme=light

[colors-light]
foreground=4c4f69
background=eff1f5

cursor=eff1f5 dc8a78
selection-foreground=4c4f69
selection-background=bcc0cc

# black
regular0=5c5f77

# red
regular1=d20f39

# green
regular2=40a02b

# yellow
regular3=df8e1d

# blue
regular4=1e66f5

# magenta
regular5=ea76cb

# cyan
regular6=179299

# white / gray
regular7=acb0be

# bright black / gray
bright0=6c6f85

# bright red
bright1=d20f39

# bright green
bright2=40a02b

# bright yellow
bright3=df8e1d

# bright blue
bright4=1e66f5

# bright magenta
bright5=ea76cb

# bright cyan
bright6=179299

# bright white / lightest background
bright7=eff1f5
